/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author laboratorio
 */
public class ListarFuncionarios extends javax.swing.JFrame {

    /**
     * Creates new form ListarFuncionarios
     */
    public ListarFuncionarios() {
        initComponents();
        alterarColuna();
    }

    public JButton getButton_deletar() {
        return Button_deletar;
    }

    public void setButton_deletar(JButton Button_deletar) {
        this.Button_deletar = Button_deletar;
    }

    public JButton getButton_novo() {
        return Button_novo;
    }

    public void setButton_novo(JButton Button_novo) {
        this.Button_novo = Button_novo;
    }

    public JButton getButton_update() {
        return Button_update;
    }

    public void setButton_update(JButton Button_update) {
        this.Button_update = Button_update;
    }

    public JButton getListar_button() {
        return listar_button;
    }

    public void setListar_button(JButton listar_button) {
        this.listar_button = listar_button;
    }
    public void alterarColuna(){
        jTable1.getColumnModel().getColumn(0).setWidth(100);
        jTable1.getColumnModel().getColumn(1).setWidth(100);
        jTable1.getColumnModel().getColumn(2).setWidth(100);
        jTable1.getColumnModel().getColumn(3).setWidth(100);
    }

    public JButton getjButton1() {
        return Button_novo;
    }

    public void setjButton1(JButton jButton1) {
        this.Button_novo = jButton1;
    }

    public JButton getjButton2() {
        return Button_deletar;
    }

    public void setjButton2(JButton jButton2) {
        this.Button_deletar = jButton2;
    }

    public JButton getjButton3() {
        return listar_button;
    }

    public void setjButton3(JButton jButton3) {
        this.listar_button = jButton3;
    }

    public JButton getjButton4() {
        return Button_update;
    }

    public void setjButton4(JButton jButton4) {
        this.Button_update = jButton4;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Button_novo = new javax.swing.JButton();
        Button_deletar = new javax.swing.JButton();
        listar_button = new javax.swing.JButton();
        Button_update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nome", "email", "cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(400, 300));
        jScrollPane1.setViewportView(jTable1);

        Button_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new (1).png"))); // NOI18N
        Button_novo.setText("new");

        Button_deletar.setText("deletar");

        listar_button.setText("listar");

        Button_update.setText("update");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Button_novo)
                        .addGap(18, 18, 18)
                        .addComponent(Button_deletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listar_button)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listar_button)
                    .addComponent(Button_update)
                    .addComponent(Button_deletar)
                    .addComponent(Button_novo))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_deletar;
    private javax.swing.JButton Button_novo;
    private javax.swing.JButton Button_update;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton listar_button;
    // End of variables declaration//GEN-END:variables
}
